/**
 * Material Icons mapping for Storybook and Button.
 * Uses @mui/icons-material for consistent icon rendering.
 */
import {
  Add as AddIcon,
  Close as CloseIcon,
  Comment as CommentIcon,
  Info as InfoIcon,
  Check as CheckIcon,
  Delete as DeleteIcon,
  Edit as EditIcon,
  Search as SearchIcon,
  ChevronRight as ChevronRightIcon,
  ArrowBack as ArrowBackIcon,
  OpenInNew as OpenInNewIcon,
  ErrorOutline as ErrorOutlineIcon,
  Settings as SettingsIcon,
  Tune as TuneIcon,
  Star as StarIcon,
  Warning as WarningIcon,
  ExpandMore as ExpandMoreIcon,
  Notifications as NotificationsIcon,
  Help as HelpIcon,
  Logout as LogoutIcon,
  Person as PersonIcon,
  Business as BusinessIcon,
  Dashboard as DashboardIcon,
  ShoppingCart as ShoppingCartIcon,
  LocalShipping as LocalShippingIcon,
  Description as DescriptionIcon,
  Folder as FolderIcon,
  BarChart as BarChartIcon,
  People as PeopleIcon,
  Book as BookIcon,
  ChevronLeft as ChevronLeftIcon,
} from '@mui/icons-material';

export default {
  ADD: { id: 'glyph-add', component: AddIcon },
  X: { id: 'glyph-x', component: CloseIcon },
  COMMENT: { id: 'glyph-comment', component: CommentIcon },
  INFO: { id: 'glyph-info', component: InfoIcon },
  CHECK: { id: 'glyph-check', component: CheckIcon },
  DELETE: { id: 'glyph-delete', component: DeleteIcon },
  EDIT: { id: 'glyph-edit', component: EditIcon },
  SEARCH: { id: 'glyph-search', component: SearchIcon },
  CHEVRON_RIGHT: { id: 'glyph-chevron-right', component: ChevronRightIcon },
  ARROW_LEFT: { id: 'glyph-arrow-left', component: ArrowBackIcon },
  NEW_TAB: { id: 'glyph-new-tab', component: OpenInNewIcon },
  EXCEPTION: { id: 'glyph-exception', component: ErrorOutlineIcon },
  SETTINGS: { id: 'glyph-settings', component: SettingsIcon },
  CUSTOMIZE: { id: 'glyph-customize', component: TuneIcon },
  ASTERISK: { id: 'glyph-asterisk', component: StarIcon },
  WARNING: { id: 'glyph-warning', component: WarningIcon },
  CHEVRON_DOWN: { id: 'glyph-chevron-down', component: ExpandMoreIcon },
  BELL: { id: 'glyph-bell', component: NotificationsIcon },
  HELP: { id: 'glyph-help', component: HelpIcon },
  LOGOUT: { id: 'glyph-logout', component: LogoutIcon },
  PERSON: { id: 'glyph-person', component: PersonIcon },
  BUILDING: { id: 'glyph-building', component: BusinessIcon },
  DASHBOARD: { id: 'glyph-dashboard', component: DashboardIcon },
  SHOPPING_CART: { id: 'glyph-shopping-cart', component: ShoppingCartIcon },
  TRUCK: { id: 'glyph-truck', component: LocalShippingIcon },
  DOCUMENT: { id: 'glyph-document', component: DescriptionIcon },
  FOLDER: { id: 'glyph-folder', component: FolderIcon },
  BAR_CHART: { id: 'glyph-bar-chart', component: BarChartIcon },
  PEOPLE: { id: 'glyph-people', component: PeopleIcon },
  BOOK: { id: 'glyph-book', component: BookIcon },
  CHEVRON_LEFT: { id: 'glyph-chevron-left', component: ChevronLeftIcon },
};
